#REVERSE ARRAY METHOD 1
arr = [1,2,3,4,5]
arr.reverse()
print(arr)

#REVERSE ARRAY METHOD 2
arr2 = [1,2,3,4,5]
reversed_arr = arr2[::-1] #THIS SYNTAX CREATES A NEW ARRAY THAT CONTAINS THE ELEMENTS OF arr2 IN REVERSE ORDER. THE [::-1] SLICING SYNTAX MEANS TO START FROM THE END OF THE ARRAY AND MOVE BACKWARDS TO THE BEGINNING, EFFECTIVELY REVERSING THE ORDER OF THE ELEMENTS.
print(reversed_arr)

#REVERSE ARRAY METHOD 3 , SWAP FIRST AND LAST ELEMENTS, THEN SECOND AND SECOND LAST ELEMENTS, AND SO ON UNTIL THE MIDDLE OF THE ARRAY IS REACHED. THIS METHOD MODIFIES THE ORIGINAL ARRAY IN PLACE WITHOUT USING ADDITIONAL SPACE FOR A NEW ARRAY.
arr3 = [1,2,3,4]
left = 0
right = len(arr3)-1

while left < right:
    arr3[left],arr3[right] = arr3[right],arr3[left]   #SWAP THE ELEMENTS AT THE LEFT AND RIGHT INDICES
    left +=1                                        #MOVE THE LEFT POINTER TO THE RIGHT
    right -=1
    print(arr3)               #PRINT THE ARRAY AFTER EACH SWAP TO SEE THE PROGRESS OF THE REVERSAL





