# SUM OF ARRAY !
arr = [2,4,6,8]
total = 0

for num in arr :
    total = total + num 
print(total)

# PRACTICE PROBLEM
arr2 = [1,3,5,7,9]      #THIS LINE DEFINES AN ARRAY arr2 WITH THE ELEMENTS 1, 3, 5, 7, AND 9. THIS ARRAY WILL BE USED TO CALCULATE THE SUM OF ITS ELEMENTS IN THE FOLLOWING LINES OF CODE.
total = 0

for num in arr2:
    total = total + num     #THIS LINE TAKES THE CURRENT VALUE OF total AND ADDS THE CURRENT ELEMENT num FROM THE ARRAY arr2 TO IT, THEN UPDATES total WITH THIS NEW SUM. THIS EFFECTIVELY ACCUMULATES THE SUM OF ALL ELEMENTS IN THE ARRAY AS THE LOOP ITERATES THROUGH EACH ELEMENT.

print(total)




