#SUM OF AN ARRAY WHILE LOOP !
arr = [2,4,6,8]
total = 0
i = 0 

while i<len(arr):
    total = total+arr[i] #THIS LINE TAKES THE CURRENT VALUE OF total AND ADDS THE CURRENT ELEMENT arr[i] FROM THE ARRAY arr TO IT, THEN UPDATES total WITH THIS NEW SUM. THIS EFFECTIVELY ACCUMULATES THE SUM OF ALL ELEMENTS IN THE ARRAY AS THE LOOP ITERATES THROUGH EACH ELEMENT.
    i+=1
print(total)

#PRACTICE PROBLEM
arr2 = [1,3,5,7,9]
total = 0   #THIS LINE INITIALIZES A VARIABLE total TO 0. THIS VARIABLE WILL BE USED TO ACCUMULATE THE SUM OF THE ELEMENTS IN THE ARRAY arr2 AS WE ITERATE THROUGH IT USING THE WHILE LOOP BELOW.
i = 0

while i < len(arr2):
    total = total + arr2[i]   #THIS LINE TAKES THE CURRENT VALUE OF total AND ADDS THE CURRENT ELEMENT arr2[i] FROM THE ARRAY arr2 TO IT, THEN UPDATES total WITH THIS NEW SUM. THIS EFFECTIVELY ACCUMULATES THE SUM OF ALL ELEMENTS IN THE ARRAY AS THE LOOP ITERATES THROUGH EACH ELEMENT.
    i+=1

print(total)


