#SUM OF AN ARRAY WHILE LOOP !
arr = [2,4,6,8]
total = 0   #INITIALIZE total TO 0; THIS VARIABLE WILL ACCUMULATE THE SUM OF ALL ELEMENTS
i = 0       #INITIALIZE INDEX i TO 0 TO START FROM THE FIRST ELEMENT

while i < len(arr):   #CONTINUE LOOPING UNTIL ALL ELEMENTS HAVE BEEN VISITED
    total = total + arr[i]   #ADD THE CURRENT ELEMENT arr[i] TO total
    i += 1   #MOVE TO THE NEXT ELEMENT
print(total)
